### ISSUE TITLE
Error when the GitLab project/repository doesn't have 'Pipelines' enabled

### ISSUE THREAD

**Issue by an062pa** [K-MailOrder/gitlab-migration#1]
Importing variables: jq: error (at <stdin>:1): Cannot index number with string "key"
parse error: Invalid numeric literal at line 2, column 0
Error creating variable. Got status code 400

**Comment by albuch** [comment]
Hi @an062pa,
thank you for the report, could you share an example project, or give a few more details which specific configurations you've set/unset to reproduce the issue?

**Comment by albuch** [comment]
After some digging I found the setting that you probably are referencing under Settings > General > Visibility, project features, permissions > Repository > Pipelines
I'll push a fix shortly.
