### ISSUE TITLE
Get Error:-  ./migrate.sh: line 86: ((: i<=: syntax error: operand expected (error token is "<=")

### ISSUE THREAD

**Issue by an062pa** [K-MailOrder/gitlab-migration#13]
Migrate archived projects? (yes/no): yes
Migrate group variables? (yes/no): yes
Migrate project variables? (yes/no): yes
Migrate badges? (yes/no): yes
Migrate hooks? (yes/no): yes
Migrating group 'my-test'
                Importing variables:  Done
                Importing badges:  Done
./migrate.sh: line 86: ((: i<=: syntax error: operand expected (error token is "<=")
./migrate.sh: line 86: ((: i<=: syntax error: operand expected (error token is "<=")
Skipping project outside group:

**Comment by albuch** [comment]
Could you run the script with `set +x` and post the output? Please make sure that you sanitize the output before posting it here and remove all sensitive informatione like URLs and secrets.

**Comment by an062pa** [comment]
[set -x output.txt](https://github.com/K-MailOrder/gitlab-migration/files/8844737/set.-x.output.txt)
Attached output file.

**Comment by albuch** [comment]
Fixed with #14
